import test from 'node:test';
import assert from 'node:assert/strict';
import { actOnLead, addChange, createGuest, emptyGuest, exportGuestCsv, importIntoGuest, matchForLead, matches, parseGuest, results, toGuestLead, updateLead } from '../lib/guest';
import type { ImportLead } from '../lib/types';
const now=new Date('2026-09-05T12:00:00Z');
const sample=():ImportLead=>({name:'פנייה לבדיקה',email:'test@example.invalid',service:'טיפול פנים',stopped_reason_code:'timing',stopped_reason_text:'מתאים רק בערב',preferred_time:'ערב',value_minor:85000});
function ready(){const s=createGuest(now);const m=matches(s,now)[0];assert.ok(m);return {s,id:m.lead.id,m};}
function returned(){const {s,id,m}=ready();const sent=actOnLead(s,id,'sent',m.message,now);return {s:actOnLead(sent,id,'reply','כן, מתאים לי לתאם',now),id};}
function closed(){let {s,id}=returned();s=actOnLead(s,id,'book','2026-09-06T15:30:00Z',now);s=actOnLead(s,id,'close','',now);return {s,id};}
test('guest seed has 20 fictional contacts, no real phone and no fabricated outcome',()=>{const s=createGuest(now);assert.equal(s.leads.length,20);assert.ok(s.leads.every(l=>!l.phone&&l.email?.endsWith('@example.invalid')&&l.is_demo));assert.deepEqual(results(s),{sent:0,returned:0,booked:0,closed:0,revenue:0});});
test('guest matches have a factual reason and do not contact blocked/incomplete leads',()=>{const ms=matches(createGuest(now),now);assert.ok(ms.length>=3);for(const m of ms){assert.ok(m.change.details);assert.ok(m.lead.stopped_reason_text);assert.ok(!m.lead.dnc&&!m.lead.medical_escalation&&!m.lead.needs_fix);}});
test('copying or editing a draft does not mark it sent',()=>{const {s,id,m}=ready();const next=updateLead(s,id,{draft:m.message,draftChangeId:m.change.id},'הנוסח הועתק',now);assert.equal(results(next).sent,0);assert.equal(next.leads.find(l=>l.id===id)?.status,'watching');});
test('cannot record reply before a sent message',()=>{const {s,id}=ready();assert.throws(()=>actOnLead(s,id,'reply','כן',now));});
test('sending requires an unexpired reason and duplicate send is blocked',()=>{const {s,id,m}=ready();const sent=actOnLead(s,id,'sent',m.message,now);assert.equal(results(sent).sent,1);assert.throws(()=>actOnLead(sent,id,'sent',m.message,now));assert.throws(()=>actOnLead(s,id,'sent',m.message,new Date('2026-10-20')));});
test('opt-out wins over all other progression and is detected in replies',()=>{let {s,id,m}=ready();s=actOnLead(s,id,'sent',m.message,now);s=actOnLead(s,id,'reply','לא ליצור קשר',now);assert.equal(s.leads.find(l=>l.id===id)?.status,'dnc');assert.equal(matchForLead(s,s.leads.find(l=>l.id===id)!,now),null);assert.throws(()=>actOnLead(s,id,'book','2026-09-06',now));});
test('medical reply diverts to a human instead of sales progression',()=>{let {s,id,m}=ready();s=actOnLead(s,id,'sent',m.message,now);s=actOnLead(s,id,'reply','יש לי אלרגיה, צריך בדיקה רפואית',now);assert.equal(s.leads.find(l=>l.id===id)?.status,'medical_review');assert.throws(()=>actOnLead(s,id,'close','',now));});
test('booking requires a positive reply and a valid future time',()=>{const {s,id}=returned();assert.throws(()=>actOnLead(s,id,'book','bad',now));assert.throws(()=>actOnLead(s,id,'book','2020-01-01',now));const b=actOnLead(s,id,'book','2026-09-06T15:30:00Z',now);assert.equal(results(b).booked,1);assert.equal(results(b).revenue,0);});
test('closing never manufactures income; confirmation is separate and idempotent',()=>{const {s,id}=closed();assert.equal(results(s).closed,1);assert.equal(results(s).revenue,0);for(const amount of ['-1','0','NaN','1.2','100000001'])assert.throws(()=>actOnLead(s,id,'revenue',amount,now));const paid=actOnLead(s,id,'revenue','85000',now);assert.equal(results(paid).revenue,85000);assert.throws(()=>actOnLead(paid,id,'revenue','85000',now));});
test('cannot confirm income before closing',()=>{const {s,id}=returned();assert.throws(()=>actOnLead(s,id,'revenue','85000',now));});
test('snoozed work stays out until its actual review time',()=>{const {s,id}=ready();const next=actOnLead(s,id,'snooze','',now);assert.equal(matches(next,now).some(m=>m.lead.id===id),false);});
test('dismissal does not erase the contact or change other leads',()=>{const {s,id}=ready();const next=actOnLead(s,id,'dismiss','',now);assert.equal(next.leads.length,s.leads.length);assert.equal(matches(next,now).some(m=>m.lead.id===id),false);});
test('reimport deduplicates by normalized contact and preserves opt-out',()=>{const row=sample();const first=importIntoGuest(emptyGuest('בדיקה',now),[row,row],now);assert.equal(first.inserted,1);assert.equal(first.duplicates,1);const id=first.state.leads[0].id;const blocked=actOnLead(first.state,id,'dnc','',now);const second=importIntoGuest(blocked,[row],now);assert.equal(second.state.leads.length,1);assert.equal(second.state.leads[0].dnc,true);});
test('new opt-out on reimport tightens safety without adding a contact',()=>{const row=sample();const first=importIntoGuest(emptyGuest('בדיקה',now),[row],now);const second=importIntoGuest(first.state,[{...row,dnc:true}],now);assert.equal(second.state.leads.length,1);assert.equal(second.state.leads[0].dnc,true);});
test('unknown reason and missing contact never become actionable',()=>{const s=createGuest(now);for(const row of [{...sample(),stopped_reason_code:'unknown' as const},{...sample(),email:undefined}]){const l=toGuestLead(row,false,now);assert.ok(l.needs_fix);assert.equal(matchForLead(s,l,now),null);}});
test('business changes require truthful details and valid future bounds',()=>{const {s,m}=ready();for(const starts of ['nonsense','2020-01-01'])assert.throws(()=>addChange(s,{...m.change,type:'slot',starts_at:starts},now));assert.throws(()=>addChange(s,{...m.change,type:'payment',ends_at:null},now));});
test('backup roundtrip preserves the full progression and income',()=>{const {s,id}=closed();const next=actOnLead(s,id,'revenue','85000',now);assert.deepEqual(parseGuest(JSON.stringify(next)),next);});
test('malformed or poisoned backup does not reach the interface',()=>{const s=createGuest(now);for(const v of [{...s,mainService:null},{...s,leads:[{...s.leads[0],notes:null}]},{...s,changes:[{}]},{...s,leads:[{...s.leads[0],trail:[{}]}]},{...s,leads:[{...s.leads[0],status:'__proto__'}]},{...s,leads:[s.leads[0],s.leads[0]]}])assert.throws(()=>parseGuest(JSON.stringify(v)));assert.throws(()=>parseGuest('not json'));});
test('CSV exports neutralize spreadsheet formula injection',()=>{const s=emptyGuest('בדיקה',now);s.leads.push(toGuestLead({...sample(),name:'=HYPERLINK("bad")'},false,now));assert.match(exportGuestCsv(s),/"'=HYPERLINK/);});
test('period-filtered results use actual event timestamps, not lead values',()=>{const {s,id}=closed();const next=actOnLead(s,id,'revenue','85000',now);assert.equal(results(next,14,new Date('2026-10-20')).revenue,0);assert.equal(results(next,0).revenue,85000);});
