'use client';
import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { Badge, Brand, Btn, Empty, Icon, Modal, type IconName } from './ui';
import { actOnLead, addChange, CHANGE_LABEL, createGuest, dated, displayStatus, emptyGuest, exportGuestCsv, GUEST_KEY, importIntoGuest, matchForLead, matches, parseGuest, results, STATUS, toGuestLead, uid, updateLead, type GuestLead, type GuestMatch, type GuestState } from '@/lib/guest';
import { parseCsv, csvImportErrorMessage } from '@/lib/csv';
import { clinicDateTimeInputValue, clinicLocalDateTimeToIso } from '@/lib/clinic-time';
import { concreteChangeDetails, hasConcreteTimingEvidence } from '@/lib/matching';
import { parseShekelInput, formatShekelMinor } from '@/lib/money';
import type { BusinessChange, ChangeType, ImportLead, StoppedReason } from '@/lib/types';
type Tab='today'|'leads'|'results'|'settings';
type Dialog='import'|'change'|'add'|'reset'|'restore'|null;
const NAV:{id:Tab;name:string;icon:IconName}[]=[{id:'today',name:'היום',icon:'home'},{id:'leads',name:'פניות',icon:'people'},{id:'results',name:'תוצאות',icon:'chart'}];
const FILTERS=[['all','כל הפניות'],['ready','יש סיבה לחזור'],['waiting','ממתינים לתשובה'],['positive','חזרו לשיחה'],['missing','חסר מידע'],['blocked','לא פונים']] as const;
const REASONS:Record<StoppedReason,string>={timing:'השעות לא התאימו',availability:'לא הייתה זמינות',payment:'חיפשה תשלומים',service:'השירות לא היה פעיל',requested_date:'ביקשה שנחזור בתאריך',price:'המחיר לא התאים',needs_time:'רצתה זמן לחשוב',no_response:'לא התקבלה תשובה',competitor:'בחרה מקום אחר',not_interested:'לא הייתה מעוניינת',unknown:'לא ידוע עדיין'};
function money(minor:number){return `${formatShekelMinor(minor)} ₪`;}
function friendly(e:unknown){return e instanceof Error?e.message:'משהו לא הסתדר. נסו שוב.';}
function dateText(v:string){const d=new Date(v);return Number.isFinite(d.getTime())?new Intl.DateTimeFormat('he-IL',{day:'numeric',month:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Jerusalem'}).format(d):v;}
function saveFile(name:string,content:string,type='text/csv;charset=utf-8'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function stateTone(l:GuestLead,status:string){return l.dnc||l.medical_escalation?'danger':l.needs_fix?'amber':status==='יש סיבה לחזור'||['interested','closed','booked'].includes(l.status)?'green':'';}

export default function GuestApp(){
  const [state,setState]=useState<GuestState|null>(null);const stateRef=useRef<GuestState|null>(null);
  const [tab,setTab]=useState<Tab>('today');const [filter,setFilter]=useState('all');const [search,setSearch]=useState('');const [service,setService]=useState('all');
  const [dialog,setDialog]=useState<Dialog>(null);const [selected,setSelected]=useState<string|null>(null);const [edit,setEdit]=useState<string|null>(null);
  const [toast,setToast]=useState('');const [storageWarning,setStorageWarning]=useState('');const [broken,setBroken]=useState('');const [period,setPeriod]=useState(0);const [resetMode,setResetMode]=useState<'demo'|'empty'>('demo');
  const [now,setNow]=useState(()=>new Date());const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
  function tell(text:string){setToast(text);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setToast(''),5000);}
  function commit(next:GuestState){try{localStorage.setItem(GUEST_KEY,JSON.stringify(next));setStorageWarning('');}catch{setStorageWarning('השמירה בדפדפן חסומה או מלאה. השינויים זמניים. ייצאו גיבוי לפני יציאה.');}stateRef.current=next;setState(next);}
  function run(fn:(s:GuestState)=>GuestState,message?:string){try{if(!stateRef.current)return;commit(fn(stateRef.current));if(message)tell(message);}catch(e){tell(friendly(e));}}
  useEffect(()=>{
    const url=new URL(window.location.href),t=url.searchParams.get('tab');if(['today','leads','results','settings'].includes(t||''))setTab(t as Tab);
    try{const raw=localStorage.getItem(GUEST_KEY);const next=raw?parseGuest(raw):createGuest();
      if(!raw&&url.searchParams.get('scenario')==='service'){const base=next.changes[1];next.changes.unshift({...base,id:'sample-service',type:'service',service:'טיפול לייזר',title:'השירות חזר לפעילות',details:'טיפולי הלייזר חזרו לפעילות ואפשר שוב לתאם טיפול'});}
      commit(next);
    }catch(e){if(e instanceof DOMException){setStorageWarning('הדפדפן לא מאפשר שמירה. אפשר להתנסות, אך ההתקדמות תישמר רק עד סגירת הדף.');const next=createGuest();stateRef.current=next;setState(next);}else{setBroken('הנתונים השמורים לא נקראו כראוי. לא מחקנו או איפסנו אותם.');}}
    const interval=setInterval(()=>setNow(new Date()),30000);
    const onStorage=(e:StorageEvent)=>{if(e.key===GUEST_KEY&&e.newValue){try{const next=parseGuest(e.newValue);stateRef.current=next;setState(next);tell('סביבת האורח עודכנה מלשונית אחרת.');}catch{setStorageWarning('התקבל עדכון לא תקין מלשונית אחרת. הנתונים כאן נשארו ללא שינוי.');}}};
    const onPop=()=>{const t=new URL(window.location.href).searchParams.get('tab');setTab(['today','leads','results','settings'].includes(t||'')?t as Tab:'today');};
    window.addEventListener('storage',onStorage);window.addEventListener('popstate',onPop);
    return()=>{clearInterval(interval);if(timer.current)clearTimeout(timer.current);window.removeEventListener('storage',onStorage);window.removeEventListener('popstate',onPop);};
  },[]);
  function go(next:Tab,f?:string){setTab(next);if(f)setFilter(f);setSelected(null);const u=new URL(window.location.href);u.searchParams.set('tab',next);history.pushState({},'',u);window.scrollTo({top:0,behavior:'instant'});}
  function perform(id:string,action:string,value=''){run(s=>actOnLead(s,id,action,value),'העדכון נשמר בסביבת האורח.');}
  const matchList=useMemo(()=>state?matches(state,now):[],[state,now]);
  const totals=useMemo(()=>state?results(state,period,now):{sent:0,returned:0,booked:0,closed:0,revenue:0},[state,period,now]);
  const lead=state?.leads.find(l=>l.id===selected);
  const editLead=state?.leads.find(l=>l.id===edit);
  const services=state?[...new Set(state.leads.map(l=>l.service))]:[];
  const pending=state?.leads.filter(l=>!l.dnc&&!l.medical_escalation&&!l.needs_fix&&['waiting','interested','contacted','booked','closed'].includes(l.status)&&!(l.status==='closed'&&l.revenueConfirmedAt)&&(!l.snoozedUntil||new Date(l.snoozedUntil)<=now))||[];
  const filtered=state?.leads.filter(l=>{
    const status=displayStatus(state,l,now);const eligible=matchList.some(m=>m.lead.id===l.id);
    return (service==='all'||service===l.service)&&(!search||`${l.name} ${l.phone||''} ${l.email||''} ${l.service} ${l.stopped_reason_text}`.toLowerCase().includes(search.toLowerCase()))&&
      (filter==='all'||filter==='ready'&&eligible||filter==='waiting'&&l.status==='waiting'||filter==='positive'&&['interested','contacted','booked','closed'].includes(l.status)||filter==='missing'&&l.needs_fix&&!l.dnc&&!l.medical_escalation||filter==='blocked'&&(l.dnc||l.medical_escalation));
  })||[];
  const activity=state?.leads.flatMap(l=>l.trail.slice(1).map(t=>({...t,name:l.name,leadId:l.id}))).sort((a,b)=>b.at.localeCompare(a.at)).slice(0,5)||[];
  if(broken)return <div className="sf-app sf-recovery-screen"><Brand/><Empty title="שומרים על מה שכבר עשיתם" description={broken}><Btn kind="secondary" onClick={()=>{try{saveFile('shuvflow-recovery.json',localStorage.getItem(GUEST_KEY)||'','application/json');}catch{setBroken('הדפדפן חוסם גם גישה לגיבוי. לא שינינו את הנתונים.');}}}>ייצוא הנתונים הקיימים</Btn><Btn onClick={()=>{if(window.confirm('לאפס את נתוני האורח בדפדפן הזה? פעולה זו אינה משנה נתוני חשבון.')){setBroken('');commit(createGuest());}}}>איפוס סביבת האורח</Btn></Empty></div>;
  if(!state)return <div className="sf-app sf-loading" role="status"><Brand/><span className="sf-loader"/><h1>מכינים את סביבת האורח</h1><p>בלי הרשמה. בלי סיסמה.</p></div>;
  const blocked=state.leads.filter(l=>l.dnc||l.medical_escalation).length;
  const missing=state.leads.filter(l=>l.needs_fix&&!l.dnc&&!l.medical_escalation).length;
  return <div className="sf-app">
    <a className="sf-skip" href="#workspace-main">דלגו לתוכן</a>
    <aside className="sf-sidebar"><Brand/><div className="sf-workspace-name"><span className="sf-clinic-avatar"><Icon name="plus"/></span><div><strong>{state.clinicName}</strong><small>סביבת התנסות</small></div></div><nav aria-label="ניווט במוצר">{NAV.map(n=><button key={n.id} type="button" onClick={()=>go(n.id)} className={tab===n.id?'active':''} aria-current={tab===n.id?'page':undefined}><Icon name={n.icon}/><span>{n.name}</span>{n.id==='today'&&matchList.length>0&&<b>{matchList.length}</b>}</button>)}</nav><div className="sf-sidebar-bottom"><div className="sf-local-card"><Icon name="shield"/><strong>רק בדפדפן הזה</strong><p>אין גישה לנתוני קליניקות אחרות. אין שליחה אוטומטית.</p></div><button type="button" className={`sf-sidebar-settings ${tab==='settings'?'active':''}`} onClick={()=>go('settings')}><Icon name="settings"/> הגדרות וגיבוי</button><a href="/" className="sf-sidebar-settings"><Icon name="logout"/> חזרה לאתר</a></div></aside>
    <div className="sf-workspace"><header className="sf-app-topbar"><div className="sf-mobile-brand"><Brand/></div><div className="sf-breadcrumb">סביבת העבודה <span>/</span> <strong>{tab==='settings'?'הגדרות':NAV.find(n=>n.id===tab)?.name}</strong></div><div className="sf-topbar-actions"><span className="sf-saved"><span className="sf-dot"/>{storageWarning?'שמירה זמנית':'נשמר בדפדפן'}</span><button type="button" className="sf-icon-btn sf-mobile-settings" aria-label="הגדרות וגיבוי" onClick={()=>go('settings')}><Icon name="settings"/></button><span className="sf-user-avatar" aria-label="אורח">א</span></div></header>
    <div className="sf-guest-banner"><span><Badge tone="green">אורח</Badge><strong>בלי חשבון. בלי סיסמה.</strong> הנתונים נשמרים כאן בלבד, לא בענן.</span><button type="button" onClick={()=>go('settings')}>ניהול סביבת ההתנסות <Icon name="arrow" size={15}/></button></div>
    {storageWarning&&<div className="sf-storage-alert" role="alert">{storageWarning} <button onClick={()=>saveFile('shuvflow-backup.json',JSON.stringify(state,null,2),'application/json')}>ייצוא גיבוי</button></div>}
    <main className="sf-main" id="workspace-main">
    {tab==='today'&&<>
      <div className="sf-page-head"><div><p className="sf-date">{new Intl.DateTimeFormat('he-IL',{weekday:'long',day:'numeric',month:'long',timeZone:'Asia/Jerusalem'}).format(now)}</p><h1>נחזיר היום שיחה טובה.</h1><p>הפניות כבר כאן. בואו נמצא את הרגע הנכון לחזור אליהן.</p></div><div className="sf-page-actions"><Btn kind="secondary" onClick={()=>setDialog('import')}><Icon name="upload"/> ייבוא פניות</Btn><Btn onClick={()=>setDialog('change')}><Icon name="plus"/> מה חדש במרפאה?</Btn></div></div>
      <div className="sf-overview"><button onClick={()=>go('leads','ready')}><span className="sf-metric-icon green"><Icon name="spark"/></span><div><span>עם סיבה לחזור</span><strong>{matchList.length}</strong></div><Icon name="arrow" size={17}/></button><button onClick={()=>go('leads','waiting')}><span className="sf-metric-icon"><Icon name="message"/></span><div><span>ממתינים לתשובה</span><strong>{state.leads.filter(l=>l.status==='waiting').length}</strong></div><Icon name="arrow" size={17}/></button><button onClick={()=>go('results')}><span className="sf-metric-icon"><Icon name="chart"/></span><div><span>חזרו לשיחה</span><strong>{results(state).returned}</strong></div><Icon name="arrow" size={17}/></button></div>
      <div className="sf-today-grid"><div className="sf-primary-column"><div className="sf-section-line"><h2>כדאי להתחיל כאן <span>{matchList.length}</span></h2><small>רק התאמות עם סיבה בתוקף</small></div>
      {state.leads.length===0?<Empty title="הפנייה הראשונה מתחילה כאן" description="הוסיפו פנייה או העלו קובץ. אחר כך נבדוק מה יכול להפוך אותה לרלוונטית שוב."><Btn onClick={()=>setDialog('add')}><Icon name="plus"/> הוספת פנייה</Btn><Btn kind="secondary" onClick={()=>setDialog('import')}>ייבוא מקובץ</Btn></Empty>:
      matchList.length?matchList.map((m,i)=><article className={`sf-opportunity ${i===0?'featured':''}`} key={m.lead.id}><div className="sf-opportunity-head"><div className="sf-person"><span className="sf-avatar">{m.lead.name.split(' ').map(p=>p.charAt(0)).slice(0,2).join('')}</span><div><h3>{m.lead.name}</h3><p>{m.lead.service} <span>·</span> {m.lead.is_demo?'פניית דוגמה':'נוספה מקומית'}</p></div></div><Badge tone="green"><Icon name={m.change.type==='slot'?'clock':'spark'} size={14}/>{m.change.type==='slot'?'תור שהתפנה':CHANGE_LABEL[m.change.type]}</Badge></div><div className="sf-evidence"><div><span>מה עצר את השיחה</span><p>{m.lead.stopped_reason_text}</p></div><Icon name="arrow" size={17}/><div><span>למה עכשיו</span><p>{m.change.details}</p></div></div><div className="sf-opportunity-foot"><span><Icon name="shield" size={15}/>{m.change.type==='requested_date'?'מועד החזרה שביקשה הגיע':'השירות והסיבה תואמים לעדכון'}</span><div><button type="button" className="sf-inline-btn" onClick={()=>perform(m.lead.id,'snooze')}>למחר</button><Btn onClick={()=>setSelected(m.lead.id)}>בדיקת ההודעה <Icon name="arrow" size={17}/></Btn></div></div></article>):<Empty title="אין סיבה טובה לפנות כרגע. וזה בסדר." description="לא מייצרים הודעות רק כדי לייצר פעילות. עדכנו מה השתנה במרפאה, או השלימו מידע שחסר בפניות."><Btn onClick={()=>setDialog('change')}>הוספת עדכון מהמרפאה</Btn></Empty>}
      {pending.length>0&&<section className="sf-next-steps"><div className="sf-section-line"><h2>השיחות שכבר התחילו</h2><small>הצעד הבא אצלכם</small></div>{pending.map(l=><button className="sf-pending-row" key={l.id} onClick={()=>setSelected(l.id)}><span className="sf-mini-avatar">{l.name[0]}</span><div><strong>{l.name}</strong><small>{l.service}</small></div><Badge tone={l.status==='waiting'?'':'green'}>{STATUS[l.status]}</Badge><Icon name="arrow" size={17}/></button>)}</section>}
      </div><aside className="sf-secondary-column"><section className="sf-side-panel"><div className="sf-section-line"><h2>מה חדש במרפאה</h2><Icon name="calendar"/></div><p className="sf-panel-description">אלו העובדות שהמערכת מצליבה עם הפניות.</p>{state.changes.length?state.changes.slice(0,4).map(c=><div className="sf-change-item" key={c.id}><span className="sf-change-dot"/><div><strong>{c.title}</strong><p>{c.service}</p><small>{c.type==='slot'&&c.starts_at?dateText(c.starts_at):c.ends_at?`בתוקף עד ${dateText(c.ends_at)}`:c.details}</small>{((c.type==='slot'&&c.starts_at&&new Date(c.starts_at)<=now)||(c.ends_at&&new Date(c.ends_at)<=now))&&<Badge>פג תוקף</Badge>}{c.is_demo&&<span className="sf-demo-note">עדכון לדוגמה</span>}</div></div>):<p className="sf-muted">עוד אין עדכונים. תור שהתפנה או שירות שחזר הם התחלה טובה.</p>}<button type="button" className="sf-add-fact" onClick={()=>setDialog('change')}><Icon name="plus" size={17}/> הוספת עדכון</button></section>
      <section className="sf-guard-panel"><div className="sf-section-line"><Icon name="shield"/><h2>גם לא לפנות זו החלטה.</h2></div><p>המערכת משאירה בחוץ פניות שלא נכון להחזיר עכשיו.</p><button onClick={()=>go('leads','blocked')}><span>בקשת הסרה או בדיקה רפואית</span><strong>{blocked}</strong><Icon name="arrow" size={16}/></button><button onClick={()=>go('leads','missing')}><span>חסר מידע להחלטה</span><strong>{missing}</strong><Icon name="arrow" size={16}/></button></section>
      {activity.length>0?<section className="sf-side-panel"><h2>מה קרה לאחרונה</h2><div className="sf-mini-timeline">{activity.map(a=><button key={a.id} type="button" onClick={()=>setSelected(a.leadId)}><strong>{a.name}</strong><span>{a.text}</span><small>{dateText(a.at)}</small></button>)}</div></section>:<div className="sf-start-note"><Icon name="message"/><p><strong>התנסות בלי הפתעות.</strong><br/>התחילו ב״בדיקת ההודעה״. בודקים נוסח, מעתיקים, ורק אז מתעדים מה קרה.</p></div>}
      </aside></div>
      <p className="sf-bottom-note">{state.leads.filter(l=>l.is_demo).length} פניות בדויות בסביבת ההתנסות. אין שליחה, גבייה או חיבור ליומן אוטומטיים.</p>
    </>}
    {tab==='leads'&&<>
      <div className="sf-page-head"><div><p className="sf-date">הכול במקום אחד</p><h1>מאחורי כל פנייה, יש סיפור.</h1><p>{state.leads.length} פניות בסביבה הזו. המידע שעוזר להבין מתי נכון לפתוח שוב את השיחה.</p></div><div className="sf-page-actions"><Btn kind="secondary" onClick={()=>setDialog('import')}><Icon name="upload"/> ייבוא קובץ</Btn><Btn onClick={()=>setDialog('add')}><Icon name="plus"/> פנייה חדשה</Btn></div></div>
      <div className="sf-list-toolbar"><label className="sf-search"><Icon name="search"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="חיפוש שם, שירות או פרטי קשר" aria-label="חיפוש פניות"/>{search&&<button type="button" aria-label="ניקוי חיפוש" onClick={()=>setSearch('')}><Icon name="close" size={15}/></button>}</label><select aria-label="סינון לפי שירות" value={service} onChange={e=>setService(e.target.value)}><option value="all">כל השירותים</option>{services.map(s=><option key={s}>{s}</option>)}</select><Btn kind="secondary" onClick={()=>{saveFile('shuvflow-leads.csv',exportGuestCsv(state));tell('יוצאו כל הפניות בסביבה הזו.');}}><Icon name="download"/> ייצוא כל הפניות</Btn></div>
      <div className="sf-filter-tabs" role="group" aria-label="סינון פניות">{FILTERS.map(([id,text])=><button key={id} aria-pressed={filter===id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{text}</button>)}</div>
      <div className="sf-lead-list-head"><span>{filtered.length} פניות מוצגות</span><small>לחצו על פנייה לפתיחת הסיפור והפעולה הבאה.</small></div>
      {filtered.length?<div className="sf-lead-table"><div className="sf-table-head"><span>הפנייה</span><span>מה עצר את השיחה</span><span>מצב</span><span>שווי משוער</span><span/></div>{filtered.map(l=>{const status=displayStatus(state,l,now);return <button className="sf-lead-row" type="button" key={l.id} onClick={()=>setSelected(l.id)}><span className="sf-table-person"><span className="sf-mini-avatar">{l.name[0]}</span><span><strong>{l.name}</strong><small>{l.service} {l.is_demo?'· דוגמה':''}</small></span></span><span className="sf-table-reason">{l.stopped_reason_text}</span><span><Badge tone={stateTone(l,status)}>{status}</Badge></span><span className="sf-table-value">{money(l.value_minor)}</span><Icon name="arrow" size={17}/></button>;})}</div>:<Empty title={state.leads.length?'לא נמצאו פניות בסינון הזה':'עוד אין כאן פניות'} description={state.leads.length?'נסו שם אחר או חזרו לכל הפניות.':'הוסיפו פנייה ידנית או ייבאו קובץ כדי להתחיל.'}><Btn onClick={()=>{if(state.leads.length){setSearch('');setFilter('all');setService('all');}else setDialog('add');}}>{state.leads.length?'ניקוי סינון':'הוספת פנייה'}</Btn></Empty>}
      <p className="sf-bottom-note">שווי משוער אינו הכנסה. פניות עם בקשת הסרה או בדיקה רפואית לא מקבלות הודעות.</p>
    </>}
    {tab==='results'&&<>
      <div className="sf-page-head"><div><p className="sf-date">לא סופרים הבטחות</p><h1>מה באמת חזר למסלול?</h1><p>רק פעולות שתיעדתם. הכנסה רק אחרי שאישרתם.</p></div><select className="sf-period" aria-label="תקופת התוצאות" value={period} onChange={e=>setPeriod(Number(e.target.value))}><option value={0}>כל התקופה</option><option value={14}>14 הימים האחרונים</option><option value={30}>30 הימים האחרונים</option></select></div>
      <div className="sf-results-disclaimer"><Icon name="file"/><span><strong>תוצאות סביבת האורח.</strong> אלו נתוני התנסות מקומיים, לא דוח הכנסות מאומת של קליניקה.</span></div>
      <div className="sf-results-grid"><section className="sf-revenue-panel"><span className="sf-label">הכנסה שאושרה בהתנסות</span><strong className="sf-revenue-total">{money(totals.revenue)}</strong><p>בלי הכנסה משוערת.<br/>בלי לספור אותה סגירה פעמיים.</p><span className="sf-revenue-foot"><Icon name="shield" size={18}/> כל סכום מקושר לפנייה ולתיעוד.</span></section><section className="sf-funnel"><h2>מהודעה לתוצאה</h2>{[{name:'תועדה שליחה',n:totals.sent},{name:'חזרו לשיחה',n:totals.returned},{name:'נקבע תור',n:totals.booked},{name:'נסגרו',n:totals.closed}].map((s,i)=><div className="sf-funnel-row" key={s.name}><span>{s.name}</span><div className="sf-funnel-track"><div style={{transform:`scaleX(${s.n/Math.max(totals.sent,totals.returned,totals.booked,totals.closed,1)})`,opacity:1-i*.15}}/></div><strong>{s.n}</strong></div>)}<p>כל שלב נספר לפי מועד התיעוד שלו בתקופה שנבחרה.</p></section></div>
      <section className="sf-result-ledger"><div className="sf-section-line"><h2>כל התיעוד, מכל התקופות</h2><Btn kind="text" onClick={()=>saveFile('shuvflow-results.csv',exportGuestCsv(state))}><Icon name="download" size={17}/> ייצוא</Btn></div>{state.leads.some(l=>l.sentAt)?state.leads.filter(l=>l.sentAt).map(l=><button className="sf-ledger-row" key={l.id} onClick={()=>setSelected(l.id)}><span><strong>{l.name}</strong><small>{l.service}</small></span><Badge tone="green">{STATUS[l.status]}</Badge><strong>{l.revenueConfirmedAt?money(l.revenueMinor||0):l.status==='closed'?'ממתינה לאישור הכנסה':'אין הכנסה מאושרת'}</strong><Icon name="arrow" size={17}/></button>):<Empty title="התוצאות הראשונות יופיעו כאן" description="פתחו פנייה במסך היום, בדקו את ההודעה ותעדו מה קרה. אין מספרי הצלחה שמולאו מראש."><Btn onClick={()=>go('today')}>בחזרה להזדמנויות <Icon name="arrow"/></Btn></Empty>}</section>
    </>}
    {tab==='settings'&&<>
      <div className="sf-page-head"><div><p className="sf-date">הסביבה שלכם, בשליטה שלכם</p><h1>הגדרות וגיבוי.</h1><p>מצב אורח לא דורש חשבון, ולא שומר נתונים בענן.</p></div></div><div className="sf-settings-grid"><section className="sf-side-panel"><h2>המרפאה בהתנסות</h2><form className="sf-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(s=>({...s,clinicName:String(f.get('clinic')||'').trim()||'הקליניקה שלי',mainService:String(f.get('service')||'').trim()||'טיפול פנים'}),'פרטי המרפאה עודכנו.');}}><label>שם המרפאה<input name="clinic" defaultValue={state.clinicName} required maxLength={80}/></label><label>השירות המרכזי<input name="service" defaultValue={state.mainService} required maxLength={80}/></label><Btn type="submit">שמירת פרטים</Btn></form></section><section className="sf-side-panel"><h2>ההתקדמות נשארת אצלכם</h2><p className="sf-muted">המידע נשמר באחסון המקומי של הדפדפן. ניקוי נתוני גלישה, מעבר למכשיר אחר או גלישה פרטית עשויים למחוק אותו. גיבוי מכיל את הפניות, ההערות והפעולות שלכם.</p><div className="sf-settings-actions"><Btn kind="secondary" onClick={()=>saveFile('shuvflow-backup.json',JSON.stringify(state,null,2),'application/json')}><Icon name="download"/> הורדת גיבוי מלא</Btn><Btn kind="secondary" onClick={()=>setDialog('restore')}><Icon name="upload"/> שחזור מגיבוי</Btn></div><p className="sf-field-help">אל תזינו פרטים רפואיים או מידע רגיש בסביבת האורח. אין שיתוף בין מכשירים ואין ניהול הרשאות.</p></section><section className="sf-side-panel"><h2>להתחיל נקי, בלי עוד משתמש</h2><p className="sf-muted">האיפוס חל רק על מצב האורח בדפדפן הזה. חשבון קיים ונתוני Supabase אינם משתנים.</p><div className="sf-settings-actions"><Btn kind="secondary" onClick={()=>{setResetMode('demo');setDialog('reset');}}><Icon name="refresh"/> התחלה מחדש עם דוגמאות</Btn><Btn kind="danger" onClick={()=>{setResetMode('empty');setDialog('reset');}}>מעבר לסביבה ריקה</Btn></div></section><section className="sf-side-panel"><h2>מה מחובר ומה לא</h2><div className="sf-capability"><Icon name="check"/><span>פניות, התאמות, הערות וייצוא מקומיים</span></div><div className="sf-capability"><Icon name="check"/><span>תיעוד ידני של שיחות, תורים והכנסות</span></div><div className="sf-capability muted"><Icon name="close"/><span>אין שליחה או סנכרון WhatsApp</span></div><div className="sf-capability muted"><Icon name="close"/><span>אין סנכרון ליומן, סליקה או חשבוניות</span></div><a className="sf-text-link" href="/login/">לכניסה לחשבון הקיים <Icon name="arrow" size={17}/></a></section></div>
    </>}
    </main><footer className="sf-app-footer"><span>Shuv Flow</span><span>אין סיבה. אין הודעה.</span><a href="/privacy/">פרטיות</a></footer></div>
    <nav className="sf-mobile-nav" aria-label="ניווט בנייד">{NAV.map(n=><button key={n.id} aria-current={tab===n.id?'page':undefined} className={tab===n.id?'active':''} onClick={()=>go(n.id)}><Icon name={n.icon}/>{n.name}{n.id==='today'&&matchList.length>0&&<i>{matchList.length}</i>}</button>)}</nav>
    {toast&&<div className="sf-toast" role="status"><Icon name="check" size={18}/>{toast}<button type="button" onClick={()=>setToast('')} aria-label="סגירת הודעה"><Icon name="close" size={16}/></button></div>}
    {lead&&!edit&&<LeadDetail state={state} lead={lead} now={now} onClose={()=>setSelected(null)} onEdit={()=>setEdit(lead.id)} perform={perform} commit={commit} notify={tell}/>}
    {(dialog==='add'||editLead)&&<LeadForm state={state} lead={editLead} onClose={()=>{setDialog(null);setEdit(null);}} onSave={row=>{try{const next=toGuestLead(row,!!editLead?.is_demo);if(editLead){const patch={...next,id:editLead.id,status:editLead.status,is_demo:editLead.is_demo,trail:editLead.trail,created_at:editLead.created_at,dnc:editLead.dnc||next.dnc,medical_escalation:editLead.medical_escalation||next.medical_escalation};if(patch.dnc)patch.status='dnc';else if(patch.medical_escalation)patch.status='medical_review';commit(updateLead(state,editLead.id,patch,'פרטי הפנייה הושלמו ידנית.'));}else{const out=importIntoGuest(state,[row]);commit(out.state);tell(out.inserted?'הפנייה נוספה.':'הפנייה כבר קיימת. לא נוצרה כפילות.');}setDialog(null);setEdit(null);}catch(e){throw e;}}}/>}
    {dialog==='import'&&<ImportDialog state={state} onClose={()=>setDialog(null)} onImport={rows=>{const result=importIntoGuest(state,rows);commit(result.state);setDialog(null);go('leads');tell(`נוספו ${result.inserted} פניות, עודכנו ${result.updated}, דולגו ${result.duplicates} כפילויות.`);}}/>}
    {dialog==='change'&&<ChangeDialog state={state} onClose={()=>setDialog(null)} onSave={c=>{const next=addChange(state,c);commit(next);setDialog(null);const count=matches(next).filter(m=>m.change.id===c.id).length;tell(count?`${count} פניות מתאימות לעדכון הזה.`:'העדכון נשמר. כרגע אין פניות שמתאימות לו.');}}/>}
    {dialog==='reset'&&<Modal title="לאפס את סביבת האורח?" onClose={()=>setDialog(null)}><div className="sf-form"><p>הפניות והפעולות המקומיות יוחלפו {resetMode==='demo'?'ב־20 פניות דוגמה חדשות':'בסביבה ריקה'}. אין אפשרות לבטל בלי גיבוי.</p><Btn kind="secondary" onClick={()=>saveFile('shuvflow-backup.json',JSON.stringify(state,null,2),'application/json')}><Icon name="download"/> להוריד גיבוי לפני האיפוס</Btn><div className="sf-form-actions"><Btn kind="danger" onClick={()=>{commit(resetMode==='demo'?createGuest():emptyGuest(state.clinicName));setDialog(null);go('today');tell('סביבת האורח אופסה.');}}>אישור ואיפוס</Btn><Btn kind="secondary" onClick={()=>setDialog(null)}>ביטול</Btn></div></div></Modal>}
    {dialog==='restore'&&<RestoreDialog onClose={()=>setDialog(null)} onRestore={s=>{commit(s);setDialog(null);go('today');tell('הגיבוי שוחזר בדפדפן הזה.');}}/>}
  </div>;
}

function LeadDetail({state,lead,now,onClose,onEdit,perform,commit,notify}:{state:GuestState;lead:GuestLead;now:Date;onClose:()=>void;onEdit:()=>void;perform:(id:string,action:string,value?:string)=>void;commit:(s:GuestState)=>void;notify:(s:string)=>void}){
  const m=matchForLead(state,lead,now);const [body,setBody]=useState(m?.message||lead.draft||'');const [ack,setAck]=useState(false);const [reply,setReply]=useState('');const [note,setNote]=useState('');const [booking,setBooking]=useState(`${dated(2)}T17:00`);const [amount,setAmount]=useState('');const [revenueAck,setRevenueAck]=useState(false);const [closeAck,setCloseAck]=useState(false);const area=useRef<HTMLTextAreaElement>(null);
  useEffect(()=>{setBody(m?.message||lead.draft||'');setAck(false);},[lead.id,m?.change.id]);
  const blocked=lead.dnc||lead.medical_escalation;const status=displayStatus(state,lead,now);
  async function copy(){if(!m)return;try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(body);else{area.current?.focus();area.current?.select();if(!document.execCommand('copy'))throw new Error('לא ניתן להעתיק');}commit(updateLead(state,lead.id,{draft:body,draftChangeId:m.change.id},'נוסח הועתק. עדיין לא תועדה שליחה.'));notify('הנוסח הועתק. לא נשלחה הודעה ולא סומנה שליחה.');}catch{area.current?.focus();area.current?.select();notify('ההעתקה האוטומטית חסומה. סמנו והעתיקו את הנוסח ידנית.');}}
  return <Modal title={lead.name} subtitle={`${lead.service} · ${lead.is_demo?'פנייה בדויה להתנסות':'פנייה מקומית בדפדפן'}`} onClose={onClose} wide>
    <div className="sf-detail-meta"><Badge tone={stateTone(lead,status)}>{status}</Badge><span>שווי משוער: {money(lead.value_minor)}</span><button className="sf-inline-btn" type="button" onClick={onEdit}>עריכת פרטים</button></div>
    <div className="sf-detail-context"><div><small>מה אנחנו יודעים</small><p>{lead.stopped_reason_text}</p>{lead.notes&&<span>{lead.notes}</span>}</div><div><small>פרטי קשר</small><p dir="ltr">{lead.phone||lead.email||'חסרים פרטי קשר'}</p>{lead.is_demo&&<span>כתובת דוגמה לא פעילה. אין שליחה ממנה.</span>}</div></div>
    {blocked?<div className="sf-safety-box"><Icon name="shield" size={27}/><h3>{lead.dnc?'לא יוצרים קשר עם הפנייה הזו.':'נדרשת בדיקה של הצוות הרפואי.'}</h3><p>{lead.dnc?'בקשת הסרה גוברת על כל התאמה. אין הודעה להכנה או לשליחה.':'לא מייצרים תשובה רפואית ולא ממשיכים בפנייה שיווקית. העבירו את המקרה לאיש מקצוע דרך הערוץ המאושר במרפאה.'}</p></div>:
    lead.needs_fix?<Empty title="חסר מידע לפני שחוזרים לשיחה" description="צריך לדעת איך ליצור קשר ומה עצר את הפנייה. לא ננחש את הפרטים החסרים."><Btn onClick={onEdit}>השלמת פרטים</Btn></Empty>:
    m?<div className="sf-compose"><div className="sf-compose-why"><Icon name="spark"/><div><strong>הסיבה לחזור עכשיו</strong><p>{m.change.details}</p><small>{m.reason}</small></div></div><label className="sf-editor-label" htmlFor="message-body">נוסח לבדיקה ולעריכה <span>מבוסס על המידע בפנייה</span></label><textarea ref={area} id="message-body" rows={5} value={body} maxLength={3000} onChange={e=>{setBody(e.target.value);setAck(false);}}/><div className="sf-copy-line"><Btn kind="secondary" onClick={copy} disabled={!body.trim()}><Icon name="copy"/> העתקת הנוסח</Btn><span>העתקה אינה שליחה.</span></div><div className="sf-send-record"><label className="sf-checkbox"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/><span>{lead.is_demo?'אני מדמה שליחה כדי לבדוק את המשך התהליך':'שלחתי את ההודעה מחוץ למערכת, ומותר לפנות לנמען הזה'}</span></label><Btn disabled={!ack||!body.trim()} onClick={()=>perform(lead.id,'sent',body)}>{lead.is_demo?'תיעוד שליחה לדוגמה':'תיעוד שליחה ידנית'} <Icon name="arrow"/></Btn></div><div className="sf-detail-secondary"><button onClick={()=>{perform(lead.id,'snooze');onClose();}} type="button">להזכיר לי מחר</button><button onClick={()=>perform(lead.id,'dismiss')} type="button">הסיבה לא מתאימה לפנייה הזו</button></div></div>:
    lead.status==='waiting'?<div className="sf-response-panel"><h3>הכדור בצד השני.</h3><p>הנוסח תועד כנשלח. כשמתקבלת תשובה, מתעדים אותה כאן.</p><label className="sf-editor-label" htmlFor="response-text">מה הפנייה ענתה?</label><textarea id="response-text" value={reply} rows={3} maxLength={2000} placeholder="למשל: כן, אשמח לשמוע עוד ולבדוק תור" onChange={e=>setReply(e.target.value)}/><div className="sf-form-actions"><Btn disabled={!reply.trim()} onClick={()=>perform(lead.id,'reply',reply)}>חזרה לשיחה <Icon name="check"/></Btn><Btn kind="secondary" onClick={()=>perform(lead.id,'not_now')}>לא מתאים כרגע</Btn><Btn kind="text" onClick={()=>perform(lead.id,'no_reply')}>לא התקבלה תשובה</Btn></div><p className="sf-field-help">בקשת הסרה או תוכן שמצריך בדיקה רפואית יעצרו את ההמשך, גם בלחיצה על ״חזרה לשיחה״.</p></div>:
    ['interested','contacted'].includes(lead.status)?<div className="sf-response-panel"><Badge tone="green"><Icon name="check" size={15}/> חזרה לשיחה</Badge><h3>עכשיו הופכים את השיחה לתור.</h3>{lead.response_text&&<blockquote>{lead.response_text}</blockquote>}<label className="sf-field">מועד התור, לפי שעון ישראל<input type="datetime-local" value={booking} onChange={e=>setBooking(e.target.value)} min={clinicDateTimeInputValue()}/></label><Btn onClick={()=>{try{perform(lead.id,'book',clinicLocalDateTimeToIso(booking));}catch{notify('בחרו מועד תקין.');}}}><Icon name="calendar"/> תיעוד תור שנקבע</Btn><p className="sf-field-help">זהו תיעוד בלבד. לא נשלחת הזמנה ולא מתבצע סנכרון ליומן.</p></div>:
    lead.status==='booked'?<div className="sf-response-panel"><Badge tone="green">נקבע תור</Badge><h3>התור מתועד.</h3><p>{lead.bookedAt&&dateText(lead.bookedAt)}</p><label className="sf-checkbox"><input type="checkbox" checked={closeAck} onChange={e=>setCloseAck(e.target.checked)}/><span>הפנייה נסגרה, ואני רוצה לתעד את הסגירה</span></label><Btn disabled={!closeAck} onClick={()=>perform(lead.id,'close')}>סימון כסגורה <Icon name="check"/></Btn><p className="sf-field-help">סגירה לבדה לא מוסיפה הכנסה. מאשרים סכום בצעד הבא.</p></div>:
    lead.status==='closed'?<div className="sf-response-panel"><Badge tone="green">הפנייה חזרה למסלול</Badge><h3>{lead.revenueConfirmedAt?'הסכום תועד. אין ספירה כפולה.':'נסגרה. כמה באמת התקבל?'}</h3>{lead.revenueConfirmedAt?<strong className="sf-confirmed-money">{money(lead.revenueMinor||0)}</strong>:<><label className="sf-field">הסכום שהתקבל בשקלים<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="למשל 850"/></label><label className="sf-checkbox"><input type="checkbox" checked={revenueAck} onChange={e=>setRevenueAck(e.target.checked)}/><span>זה הסכום שהתקבל, ולא שווי פוטנציאלי</span></label><Btn disabled={!revenueAck||!parseShekelInput(amount)} onClick={()=>perform(lead.id,'revenue',String(parseShekelInput(amount)))}>אישור הכנסה בנפרד <Icon name="check"/></Btn><p className="sf-field-help">בסביבת אורח הסכום מופיע כתוצאת התנסות בלבד. אין סליקה או הפקת חשבונית.</p></>}</div>:
    <Empty title={lead.snoozedUntil&&new Date(lead.snoozedUntil)>now?'נחזור לבדיקה במועד שקבעתם':'כרגע אין סיבה טובה לחזור'} description={lead.snoozedUntil&&new Date(lead.snoozedUntil)>now?`הפנייה תיבדק שוב אחרי ${dateText(lead.snoozedUntil)}.`:'המערכת לא מכינה הודעה כשאין התאמה לעדכון בתוקף. אפשר להשלים מידע או לעדכן מה השתנה במרפאה.'}/>}
    <details className="sf-detail-history"><summary>הסיפור המלא <span>{lead.trail.length} עדכונים</span></summary><ol>{[...lead.trail].reverse().map(t=><li key={t.id}><span>{t.text}</span><time>{dateText(t.at)}</time></li>)}</ol></details>
    <form className="sf-note-form" onSubmit={e=>{e.preventDefault();perform(lead.id,'note',note);setNote('');}}><input value={note} onChange={e=>setNote(e.target.value)} placeholder="הערה פנימית לצעד הבא" aria-label="הערה פנימית" maxLength={2000}/><Btn type="submit" kind="secondary" disabled={!note.trim()}>הוספה</Btn></form>
    {!lead.dnc&&<button className="sf-dnc-action" type="button" onClick={()=>{if(window.confirm('לתעד בקשה לא ליצור קשר ולחסום פנייה חוזרת?'))perform(lead.id,'dnc');}}><Icon name="shield" size={15}/> התקבלה בקשה לא ליצור קשר</button>}
  </Modal>;
}

function LeadForm({state,lead,onClose,onSave}:{state:GuestState;lead?:GuestLead;onClose:()=>void;onSave:(row:ImportLead)=>void}){
  const [error,setError]=useState('');const [reason,setReason]=useState<StoppedReason>(lead?.stopped_reason_code||'unknown');
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const f=new FormData(e.currentTarget);const str=(k:string)=>String(f.get(k)||'').trim();const value=str('value')?parseShekelInput(str('value')):0;
    if(value===null){setError('השווי צריך להיות סכום תקין בשקלים.');return;}
    if(reason==='timing'&&!hasConcreteTimingEvidence(str('preferred'))){setError('כתבו העדפה ברורה, למשל ערב, בוקר או אחרי 18:00.');return;}
    if(reason==='requested_date'&&!str('requested')){setError('צריך לציין את המועד שבו ביקשו לחזור.');return;}
    try{onSave({name:str('name'),phone:str('phone'),email:str('email'),service:str('service'),value_minor:value,stopped_reason_code:reason,stopped_reason_text:str('reasonText')||REASONS[reason],notes:str('notes'),branch:str('branch'),preferred_time:str('preferred'),requested_contact_after:str('requested'),dnc:!!lead?.dnc,medical_escalation:!!lead?.medical_escalation,needs_fix:reason==='unknown',external_ref:lead?.external_ref||undefined});}catch(err){setError(friendly(err));}}
  return <Modal title={lead?'להשלים את הסיפור':'פנייה חדשה, התחלה מסודרת'} subtitle="רק פרטים שעוזרים להחליט למי לחזור. בלי מידע רפואי." onClose={onClose}><form className="sf-form" onSubmit={submit}>
    <label>שם הפונה<input name="name" defaultValue={lead?.name} required maxLength={100}/></label><div className="sf-form-grid"><label>טלפון<input name="phone" type="tel" dir="ltr" defaultValue={lead?.phone||''} placeholder="0501234567" maxLength={20}/></label><label>אימייל<input name="email" type="email" dir="ltr" defaultValue={lead?.email||''} placeholder="name@example.com" maxLength={180}/></label></div><p className="sf-field-help">נדרש טלפון או אימייל תקין כדי שהפנייה תהיה מוכנה לחזרה.</p><div className="sf-form-grid"><label>שירות<input name="service" required maxLength={100} defaultValue={lead?.service||state.mainService} list="service-options"/><datalist id="service-options">{[...new Set(state.leads.map(l=>l.service))].map(s=><option key={s} value={s}/>)}</datalist></label><label>שווי משוער בשקלים<input name="value" inputMode="decimal" defaultValue={lead?lead.value_minor/100:''} placeholder="לא חובה"/></label></div><label>למה השיחה נעצרה?<select value={reason} onChange={e=>setReason(e.target.value as StoppedReason)}>{Object.entries(REASONS).map(([code,text])=><option key={code} value={code}>{text}</option>)}</select></label><label>מה נאמר בפועל?<input name="reasonText" key={reason} defaultValue={lead?.stopped_reason_code===reason?lead.stopped_reason_text:REASONS[reason]} maxLength={500} placeholder="למשל: יכולה להגיע רק אחרי העבודה"/></label>{reason==='timing'&&<label>שעות או ימים שמתאימים<input name="preferred" defaultValue={lead?.preferred_time||''} required placeholder="למשל: ערב, או אחרי 18:00"/></label>}{reason==='requested_date'&&<label>מועד החזרה שביקשו<input name="requested" type="date" defaultValue={lead?.requested_contact_after||''} required/></label>}<label>סניף, רק כשיש הגבלה<input name="branch" maxLength={80} defaultValue={lead?.branch||''} placeholder="לא חובה"/></label><label>הערה מהשיחה<textarea name="notes" rows={2} maxLength={2000} defaultValue={lead?.notes||''}/></label>{error&&<p className="sf-form-error" role="alert">{error}</p>}<div className="sf-form-actions"><Btn type="submit">{lead?'שמירת הפרטים':'הוספת הפנייה'}</Btn><Btn kind="secondary" onClick={onClose}>ביטול</Btn></div>
  </form></Modal>;
}

function ImportDialog({state,onClose,onImport}:{state:GuestState;onClose:()=>void;onImport:(rows:ImportLead[])=>void}){
  const [text,setText]=useState('');const [name,setName]=useState('');const [parsed,setParsed]=useState<ReturnType<typeof parseCsv>|null>(null);const [error,setError]=useState('');const [ack,setAck]=useState(false);const [busy,setBusy]=useState(false);
  const sample='שם,אימייל,שירות,סיבת עצירה,זמן מועדף,שווי,לא ליצור קשר\nנועה לדוגמה,noa@example.invalid,טיפול פנים,מחפשת תור ערב,ערב,850,לא\nדניאל לדוגמה,daniel@example.invalid,הסרת שיער,חיפש תשלומים,,1200,לא\nרוני לדוגמה,roni@example.invalid,טיפול פנים,ביקשה לא ליצור קשר,,700,כן';
  function analyze(source:string){setText(source);setParsed(null);setError('');setAck(false);try{if(source.length>2000000)throw new Error('הקובץ גדול מדי. בחרו CSV עד 2MB.');const p=parseCsv(source,state.mainService);if(p.valid.length+p.needsFix.length>1000)throw new Error('אפשר לייבא עד 1,000 פניות לסביבת אורח.');setParsed(p);}catch(e){setError(csvImportErrorMessage(e)||friendly(e));}}
  const rows=parsed?[...parsed.valid,...parsed.needsFix]:[];
  return <Modal title="הפניות שלכם, בלי להתחיל מחדש" subtitle="CSV בעברית או באנגלית. בודקים הכול לפני שמכניסים לסביבה." onClose={onClose} wide><div className="sf-form">
    <label className="sf-upload-zone"><Icon name="upload" size={30}/><strong>{busy?'קוראים את הקובץ…':name||'בחרו קובץ פניות'}</strong><span>CSV עד 2MB · עד 1,000 פניות</span><input type="file" accept=".csv,text/csv" aria-label="בחירת קובץ CSV" disabled={busy} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>2000000){setError('הקובץ גדול מדי. בחרו קובץ עד 2MB.');return;}setBusy(true);setName(f.name);try{analyze(await f.text());}catch{setError('לא ניתן לקרוא את הקובץ.');}finally{setBusy(false);}}}/></label>
    <div className="sf-import-help"><p><strong>כותרות חובה:</strong> שם, ובנוסף טלפון או אימייל.<br/>מומלץ גם: שירות, סיבת עצירה, זמן מועדף, מועד לחזרה, שווי, הערות.</p><button className="sf-inline-btn" onClick={()=>saveFile('shuvflow-template.csv','\uFEFF'+sample)}><Icon name="download" size={16}/> תבנית לדוגמה</button></div>
    <details className="sf-paste"><summary>או להדביק תוכן CSV</summary><textarea aria-label="תוכן CSV להדבקה" rows={4} value={text} onChange={e=>{setText(e.target.value);setParsed(null);setAck(false);}} placeholder={sample}/><Btn kind="secondary" onClick={()=>analyze(text)}>בדיקת התוכן</Btn></details>
    {error&&<p className="sf-form-error" role="alert">{error}</p>}
    {parsed&&<><div className="sf-import-summary"><div><strong>{rows.length}</strong><span>פניות בקובץ</span></div><div><strong>{parsed.valid.filter(l=>!l.dnc&&!l.medical_escalation).length}</strong><span>עם מידע מספיק</span></div><div><strong>{parsed.needsFix.filter(l=>!l.dnc&&!l.medical_escalation).length}</strong><span>להשלמת פרטים</span></div><div><strong>{rows.filter(l=>l.dnc||l.medical_escalation).length}</strong><span>לא פונים</span></div></div><div className="sf-import-preview" aria-label="תצוגה מקדימה לפני הייבוא">{rows.slice(0,8).map((l,i)=><div key={i}><span><strong>{l.name}</strong><small>{l.service}</small></span><Badge tone={l.dnc||l.medical_escalation?'danger':l.needs_fix?'amber':'green'}>{l.dnc?'לא ליצור קשר':l.medical_escalation?'בדיקה רפואית':l.needs_fix?'להשלמה':'מוכן'}</Badge></div>)}</div>{rows.length>8&&<small>מוצגות 8 הפניות הראשונות מתוך {rows.length}.</small>}<p className="sf-field-help">כפילויות מזוהות לפי פרטי הקשר. ייבוא חוזר לא מוחק התקדמות ולא מבטל בקשת הסרה. פניות שחסר בהן מידע לא יקבלו הודעה.</p><label className="sf-checkbox"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/><span>בדקתי את התצוגה. יש לי הרשאה להשתמש בנתונים, ואין כאן מידע רפואי רגיש. הנתונים יישמרו בדפדפן הזה בלבד.</span></label><Btn disabled={!ack||busy} onClick={()=>{try{onImport(rows);}catch(e){setError(friendly(e));}}}>ייבוא {rows.length} פניות לסביבת האורח <Icon name="arrow"/></Btn></>}
  </div></Modal>;
}

function ChangeDialog({state,onClose,onSave}:{state:GuestState;onClose:()=>void;onSave:(c:BusinessChange)=>void}){
  const [type,setType]=useState<ChangeType>('slot');const [error,setError]=useState('');const [verified,setVerified]=useState(false);
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const f=new FormData(e.currentTarget);const str=(k:string)=>String(f.get(k)||'').trim();try{
    let c:BusinessChange={id:uid(),organization_id:'guest-local',type,service:str('service'),branch:str('branch')||null,title:CHANGE_LABEL[type],details:str('details'),starts_at:type==='slot'?clinicLocalDateTimeToIso(str('starts')):null,ends_at:type==='slot'?null:clinicLocalDateTimeToIso(`${str('ends')}T23:59`),is_demo:true,created_at:new Date().toISOString()};
    if(type==='slot')c={...c,details:concreteChangeDetails(c)};onSave(c);
  }catch(e){setError(friendly(e));}}
  return <Modal title="מה השתנה במרפאה?" subtitle="עדכון עובדתי אחד יכול להיות סיבה טובה לחזור לפנייה הנכונה." onClose={onClose}><form className="sf-form" onSubmit={submit}>
    <div className="sf-change-choice" role="group" aria-label="סוג העדכון">{(['slot','payment','service'] as const).map(t=><button key={t} type="button" aria-pressed={type===t} className={type===t?'active':''} onClick={()=>{setType(t);setVerified(false);}}><Icon name={t==='slot'?'calendar':t==='payment'?'file':'refresh'}/>{CHANGE_LABEL[t]}</button>)}</div><label>לאיזה שירות?<input name="service" list="change-services" defaultValue={state.mainService} required maxLength={100}/><datalist id="change-services">{[...new Set(state.leads.map(l=>l.service))].map(s=><option key={s} value={s}/>)}</datalist></label>
    {type==='slot'?<label>מתי התור שהתפנה? לפי שעון ישראל<input type="datetime-local" name="starts" defaultValue={`${dated(1)}T18:30`} min={clinicDateTimeInputValue()} required/></label>:<><label>מה בדיוק השתנה?<textarea name="details" key={type} rows={3} maxLength={500} minLength={4} required placeholder={type==='payment'?'למשל: אפשר לחלק ל־3 תשלומים ללא תוספת':'למשל: הטיפול חזר לפעילות, ואפשר שוב להזמין תור'}/></label><label>עד מתי העדכון בתוקף?<input name="ends" type="date" defaultValue={dated(14)} min={dated(0)} required/></label></>}
    <label>סניף, רק אם העדכון מוגבל לסניף<input name="branch" maxLength={80} placeholder="ללא הגבלת סניף"/></label><label className="sf-checkbox"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/><span>זה העדכון שאני רוצה לבדוק בהתנסות. בפנייה אמיתית צריך לוודא שהפרטים נכונים ושמותר לפנות.</span></label>{error&&<p className="sf-form-error" role="alert">{error}</p>}<Btn type="submit" disabled={!verified}>לבדוק למי זה מתאים <Icon name="spark"/></Btn><p className="sf-field-help">גם אם אין התאמה, העדכון נשמר. לא נוצרת הודעה בלי קשר ברור למה שעצר את הפנייה.</p>
  </form></Modal>;
}
function RestoreDialog({onClose,onRestore}:{onClose:()=>void;onRestore:(s:GuestState)=>void}){
  const [next,setNext]=useState<GuestState|null>(null);const [error,setError]=useState('');const [ack,setAck]=useState(false);
  return <Modal title="שחזור סביבת אורח מגיבוי" onClose={onClose}><div className="sf-form"><p>בחרו קובץ גיבוי JSON שיוצא מ־Shuv Flow. שחזור מחליף את נתוני האורח הקיימים בדפדפן.</p><input type="file" accept=".json,application/json" aria-label="בחירת גיבוי" onChange={async e=>{setNext(null);setAck(false);setError('');try{const f=e.target.files?.[0];if(!f)return;if(f.size>5000000)throw new Error('קובץ הגיבוי גדול מדי.');setNext(parseGuest(await f.text()));}catch(e){setError(friendly(e));}}}/>{next&&<><p>נמצא גיבוי של <strong>{next.clinicName}</strong> עם {next.leads.length} פניות.</p><label className="sf-checkbox"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/><span>אני מאשר להחליף את נתוני האורח הקיימים בגיבוי הזה</span></label></>}{error&&<p className="sf-form-error" role="alert">{error}</p>}<Btn disabled={!next||!ack} onClick={()=>{if(next)onRestore(next);}}>שחזור הגיבוי</Btn></div></Modal>;
}
