"""Real browser acceptance. Runs against a locally served export OR a public deployment."""
import asyncio,json,os,shutil
from pathlib import Path
from playwright.async_api import async_playwright,expect
BASE=os.environ.get('SHUV_URL','http://127.0.0.1:3080').rstrip('/')
OUT=Path(os.environ.get('SHUV_SCREENSHOTS','qa'));OUT.mkdir(exist_ok=True,parents=True)
KEY='shuvflow-guest-v1'
async def main():
 async with async_playwright() as p:
  b=await p.chromium.launch(executable_path=shutil.which('chromium'),headless=True,args=['--no-sandbox'])
  ctx=await b.new_context(viewport={'width':1440,'height':1000},permissions=['clipboard-read','clipboard-write'])
  await ctx.add_init_script('Element.prototype.requestPointerLock=function(){};Element.prototype.setPointerCapture=function(){}')
  page=await ctx.new_page();errors=[];third_party=[];checks=[]
  page.on('pageerror',lambda e:errors.append(str(e)))
  page.on('request',lambda req:third_party.append(req.url) if 'supabase.' in req.url or 'wa.me/' in req.url else None)
  async def state():return await page.evaluate('(k)=>JSON.parse(localStorage.getItem(k))',KEY)
  async def check(name,condition):
   assert condition,name
   checks.append(name)
  response=await page.goto(BASE+'/',wait_until='networkidle')
  await check('public landing responds without Vercel authentication',response.status==200 and '/sso' not in page.url and 'vercel.com' not in page.url)
  await page.get_by_role('button',name='נוספו תשלומים',exact=True).click()
  await expect(page.locator('.sf-sample-message')).to_contain_text('3 תשלומים')
  await page.get_by_role('button',name='השירות חזר',exact=True).click()
  await expect(page.locator('.sf-sample-message')).to_contain_text('השירות חזר')
  await check('landing switch updates real sample matching',await page.locator('.sf-person-picker button').count()>0)
  await page.goto(BASE+'/guest/',wait_until='networkidle');await page.get_by_role('heading',name='נחזיר היום שיחה טובה.').wait_for()
  s=await state();await check('no signup and 20 local fictional contacts',len(s['leads'])==20 and all(l['is_demo'] for l in s['leads']))
  count=await page.locator('.sf-opportunity').count();await check('initial matches are available',count>=3)
  await page.get_by_role('button',name='בדיקת ההודעה').first.click()
  name=await page.locator('#sf-dialog-title').inner_text()
  await page.get_by_role('button',name='העתקת הנוסח',exact=True).click();await page.wait_for_timeout(150)
  s=await state();l=next(l for l in s['leads'] if l['name']==name)
  await check('copy does not send or count revenue',not l.get('sentAt') and not l.get('revenueConfirmedAt'))
  await expect(page.get_by_role('button',name='תיעוד שליחה לדוגמה')).to_be_disabled()
  await page.get_by_role('checkbox',name='אני מדמה שליחה כדי לבדוק את המשך התהליך').check()
  await page.get_by_role('button',name='תיעוד שליחה לדוגמה').click()
  await page.get_by_label('מה הפנייה ענתה?').fill('כן, מתאים לי. אשמח לתאם תור')
  await page.get_by_role('button',name='חזרה לשיחה',exact=True).click()
  await page.get_by_role('button',name='תיעוד תור שנקבע',exact=True).click()
  await expect(page.get_by_role('button',name='סימון כסגורה')).to_be_disabled()
  await page.get_by_role('checkbox',name='הפנייה נסגרה, ואני רוצה לתעד את הסגירה').check()
  await page.get_by_role('button',name='סימון כסגורה').click()
  s=await state();l=next(l for l in s['leads'] if l['name']==name)
  await check('book and close never fabricate revenue',l['status']=='closed' and not l.get('revenueConfirmedAt'))
  await page.get_by_label('הסכום שהתקבל בשקלים').fill('850')
  await expect(page.get_by_role('button',name='אישור הכנסה בנפרד')).to_be_disabled()
  await page.get_by_role('checkbox',name='זה הסכום שהתקבל, ולא שווי פוטנציאלי').check()
  await page.get_by_role('button',name='אישור הכנסה בנפרד').click()
  await expect(page.get_by_role('heading',name='הסכום תועד. אין ספירה כפולה.')).to_be_visible()
  s=await state();l=next(l for l in s['leads'] if l['name']==name)
  await check('850 shekels recorded exactly once after confirmation',l['revenueMinor']==85000)
  await page.screenshot(path=str(OUT/'journey-confirmed.png'))
  await page.get_by_role('button',name='סגירה',exact=True).click()
  await page.goto(BASE+'/guest/?tab=results',wait_until='networkidle')
  await expect(page.locator('.sf-revenue-total')).to_contain_text('850')
  await page.screenshot(path=str(OUT/'journey-results.png'))
  await page.reload(wait_until='networkidle');await expect(page.locator('.sf-revenue-total')).to_contain_text('850')
  await check('results persist across reload',True)
  await page.goto(BASE+'/guest/?tab=leads',wait_until='networkidle')
  await page.get_by_label('חיפוש פניות').fill(name)
  await expect(page.locator('.sf-lead-row')).to_have_count(1)
  await page.get_by_role('button',name='ניקוי חיפוש').click()
  await page.get_by_role('button',name='לא פונים',exact=True).click()
  await page.locator('.sf-lead-row').first.click()
  await expect(page.get_by_role('button',name='העתקת הנוסח')).to_have_count(0)
  await check('blocked records have no outreach control',True)
  await page.keyboard.press('Escape')
  await expect(page.locator('dialog')).to_have_count(0)
  await page.get_by_role('button',name='ייבוא קובץ',exact=True).click()
  await page.locator('summary',has_text='או להדביק תוכן CSV').click()
  await page.get_by_label('תוכן CSV להדבקה').fill('bad data')
  await page.get_by_role('button',name='בדיקת התוכן').click()
  await expect(page.locator('.sf-form-error')).to_be_visible()
  csv='שם,אימייל,שירות,סיבת עצירה,זמן מועדף,לא ליצור קשר\nלקוחה לבדיקה,test@example.invalid,טיפול פנים,מחפשת תור ערב,ערב,לא\nלקוחה לבדיקה,test@example.invalid,טיפול פנים,מחפשת תור ערב,ערב,לא\nחסומה לבדיקה,blocked@example.invalid,טיפול פנים,לא ליצור קשר,,כן'
  await page.get_by_label('תוכן CSV להדבקה').fill(csv);await page.get_by_role('button',name='בדיקת התוכן').click()
  await expect(page.get_by_role('button',name='ייבוא 3 פניות לסביבת האורח')).to_be_disabled()
  await page.locator('dialog input[type=checkbox]').check()
  await page.get_by_role('button',name='ייבוא 3 פניות לסביבת האורח').click()
  s=await state();await check('CSV preview, consent, dedupe and DNC survive import',len(s['leads'])==22 and any(l['name']=='חסומה לבדיקה' and l['dnc'] for l in s['leads']))
  await page.goto(BASE+'/guest/?tab=settings',wait_until='networkidle')
  await page.get_by_label('שם המרפאה').fill('מרפאת הבדיקה')
  await page.get_by_role('button',name='שמירת פרטים').click()
  await check('clinic settings update the workspace', (await state())['clinicName']=='מרפאת הבדיקה')
  await page.get_by_role('button',name='שחזור מגיבוי').click()
  await page.get_by_label('בחירת גיבוי').set_input_files({'name':'invalid.json','mimeType':'application/json','buffer':b'{"version":1}'})
  await expect(page.locator('.sf-form-error')).to_be_visible()
  await check('invalid restore keeps current workspace intact',len((await state())['leads'])==22)
  await page.keyboard.press('Escape')
  async with page.expect_download() as dl:
   await page.get_by_role('button',name='הורדת גיבוי מלא').click()
  download=await dl.value;await download.save_as(str(OUT/'browser-backup.json'))
  await check('full backup can be downloaded',json.loads((OUT/'browser-backup.json').read_text())['clinicName']=='מרפאת הבדיקה')
  await page.goto(BASE+'/login/',wait_until='domcontentloaded')
  await expect(page.get_by_role('link',name='כניסת אורח ללא הרשמה')).to_be_visible()
  await check('legacy login exposes an immediate guest escape',True)
  await check('no cloud lead access or messaging requests during guest use',len(third_party)==0)
  await check('no browser runtime errors',not errors)
  (OUT/'journey-report.json').write_text(json.dumps({'checks':checks,'errors':errors,'thirdParty':third_party},ensure_ascii=False,indent=2))
  print(json.dumps({'checks':checks,'errors':errors},ensure_ascii=False,indent=2))
  await b.close()
asyncio.run(main())
