import type { ImportLead } from "./types";

export const DEMO_LEADS: ImportLead[] = [
  { external_ref: "demo-01", name: "נועה לוי", phone: "050-555-0101", service: "טיפול פנים", value_minor: 90000, last_contact_at: "2026-08-14", notes: "ביקשה רק תור אחרי העבודה", stopped_reason_code: "timing", stopped_reason_text: "יכולה רק אחרי 17:00", preferred_time: "אחרי 17:00" },
  { external_ref: "demo-02", name: "מיכל כהן", phone: "052-555-0102", service: "טיפול פנים", value_minor: 90000, last_contact_at: "2026-08-12", notes: "אין אפשרות להגיע בבוקר", stopped_reason_code: "timing", stopped_reason_text: "מחפשת תור ערב", preferred_time: "ערב" },
  { external_ref: "demo-03", name: "יעל מזרחי", email: "yael@example.com", service: "הסרת שיער", value_minor: 160000, last_contact_at: "2026-08-10", notes: "לא הייתה זמינות לטיפול", stopped_reason_code: "availability", stopped_reason_text: "לא הייתה זמינות לטיפול" },
  { external_ref: "demo-04", name: "דנה בר", phone: "054-555-0104", service: "הזרקה אסתטית", value_minor: 140000, last_contact_at: "2026-08-08", notes: "ביקשה שנחזור בספטמבר", stopped_reason_code: "requested_date", stopped_reason_text: "ביקשה לחזור אליה בתחילת ספטמבר", requested_contact_after: "2026-09-01" },
  { external_ref: "demo-05", name: "רונית פרץ", phone: "050-555-0105", service: "טיפול פנים", value_minor: 75000, last_contact_at: "2026-08-07", notes: "יקר כרגע", stopped_reason_code: "price", stopped_reason_text: "המחיר לא התאים כרגע" },
  { external_ref: "demo-06", name: "סיון שלום", email: "sivan@example.com", service: "הסרת שיער", value_minor: 180000, last_contact_at: "2026-08-04", notes: "התעניינה במסלול תשלומים", stopped_reason_code: "payment", stopped_reason_text: "חיפשה אפשרות לתשלומים" },
  { external_ref: "demo-07", name: "אורית אלון", phone: "052-555-0107", service: "טיפול לייזר", value_minor: 120000, last_contact_at: "2026-08-03", notes: "השירות הוקפא זמנית", stopped_reason_code: "service", stopped_reason_text: "הטיפול לא היה זמין" },
  { external_ref: "demo-08", name: "מאיה רז", phone: "053-555-0108", service: "טיפול פנים", value_minor: 80000, last_contact_at: "2026-07-30", notes: "לא ענתה", stopped_reason_code: "no_response", stopped_reason_text: "לא חזרה להודעה האחרונה" },
  { external_ref: "demo-09", name: "ליאת גולן", email: "liat@example.com", service: "הזרקה אסתטית", value_minor: 170000, last_contact_at: "2026-07-28", notes: "בחרה מרפאה אחרת", stopped_reason_code: "competitor", stopped_reason_text: "בחרה בינתיים מקום אחר" },
  { external_ref: "demo-10", name: "איילת גבאי", phone: "050-555-0110", service: "טיפול פנים", value_minor: 70000, last_contact_at: "2026-07-27", notes: "ביקשה שלא נפנה", dnc: true, stopped_reason_code: "not_interested", stopped_reason_text: "ביקשה לא ליצור קשר" },
  { external_ref: "demo-11", name: "נטע לב", phone: "052-555-0111", service: "הסרת שיער", value_minor: 140000, last_contact_at: "2026-07-25", notes: "", stopped_reason_code: "unknown", stopped_reason_text: "לא ידוע למה הפנייה נעצרה", needs_fix: true },
  { external_ref: "demo-12", name: "שירה ארז", email: "shira@example.com", service: "טיפול פנים", value_minor: 65000, last_contact_at: "2026-07-24", notes: "לא חזרה להודעה האחרונה", stopped_reason_code: "no_response", stopped_reason_text: "לא חזרה להודעה האחרונה" },
  { external_ref: "demo-13", name: "קרן יוסף", phone: "054-555-0113", service: "הזרקה אסתטית", value_minor: 125000, last_contact_at: "2026-07-22", notes: "רוצה לחשוב", stopped_reason_code: "needs_time", stopped_reason_text: "רצתה זמן לחשוב" },
  { external_ref: "demo-14", name: "תמר רון", phone: "050-555-0114", service: "טיפול לייזר", value_minor: 115000, last_contact_at: "2026-07-21", notes: "רק בסניף צפון", stopped_reason_code: "availability", stopped_reason_text: "לא הייתה זמינות בסניף שביקשה", branch: "צפון" },
  { external_ref: "demo-15", name: "חן הדר", email: "chen@example.com", service: "טיפול פנים", value_minor: 85000, last_contact_at: "2026-07-19", notes: "מחכה לאישור בת הזוג", stopped_reason_code: "needs_time", stopped_reason_text: "רצתה להתייעץ לפני החלטה" },
  { external_ref: "demo-16", name: "גלית מור", phone: "052-555-0116", service: "הסרת שיער", value_minor: 150000, last_contact_at: "2026-07-18", notes: "לא רלוונטי כרגע", stopped_reason_code: "not_interested", stopped_reason_text: "אמרה שלא רלוונטי כרגע" },
  { external_ref: "demo-17", name: "רחל אבני", phone: "053-555-0117", service: "טיפול פנים", value_minor: 95000, last_contact_at: "2026-07-16", notes: "חופשה עד אמצע ספטמבר", stopped_reason_code: "requested_date", stopped_reason_text: "ביקשה לחזור אחרי החופשה", requested_contact_after: "2026-09-15" },
  { external_ref: "demo-18", name: "עדי וייס", email: "adi@example.com", service: "טיפול לייזר", value_minor: 110000, last_contact_at: "2026-07-15", notes: "רוצה יום שישי בלבד", stopped_reason_code: "timing", stopped_reason_text: "יכולה להגיע רק ביום שישי", preferred_time: "שישי" },
  { external_ref: "demo-19", name: "מירב צור", phone: "050-555-0119", service: "הזרקה אסתטית", value_minor: 155000, last_contact_at: "2026-07-13", notes: "ביקשה מידע רפואי", stopped_reason_code: "unknown", stopped_reason_text: "נדרשת בדיקה של הצוות הרפואי", needs_fix: true },
  { external_ref: "demo-20", name: "הילה אור", phone: "052-555-0120", service: "טיפול פנים", value_minor: 88000, last_contact_at: "2026-07-11", notes: "אין החלטה", stopped_reason_code: "needs_time", stopped_reason_text: "עדיין לא החליטה" },
];
