'use client';
import {useEffect,useMemo,useRef,useState,type FormEvent} from 'react';
import Image from 'next/image';
import {Icon} from '@/components/flow/ui';
import {DEMO_CONFIG,INITIAL_INPUT,businessPhone,estimate,packConfig,requestText,unpackConfig,validateConfig,whatsappLink,type IntakeConfig,type IntakeInput} from '@/lib/intake';
export function NextNav({back=false}:{back?:boolean}){return <header className="nx-nav"><a href="/next/" className="nx-brand" aria-label="Shuv, הכיוון החדש"><Image src="/shuv-flow-logo.png" width={1200} height={400} alt="Shuv Flow"/></a><span className="nx-nav-caption">פחות הלוך־חזור.</span><a className="nx-nav-action" href={back?'/next/':'/next/build/'}>{back?'חזרה לאתר':'בונים קישור'}<Icon name="arrow" size={16}/></a></header>}
export function IntakeForm({config=DEMO_CONFIG,compact=false}:{config?:IntakeConfig;compact?:boolean}){
 const [input,setInput]=useState<IntakeInput>({...INITIAL_INPUT,city:config.cities[0]});
 const [otherCity,setOtherCity]=useState('');
 const [review,setReview]=useState(false),[consent,setConsent]=useState(false),[status,setStatus]=useState('');
 const textRef=useRef<HTMLTextAreaElement>(null);
 useEffect(()=>{setInput({...INITIAL_INPUT,city:config.cities[0]});setReview(false);setConsent(false);setOtherCity('');setStatus('');},[config]);
 const effectiveInput=useMemo(()=>({...input,city:input.city==='עיר אחרת'?(otherCity.trim()||'עיר אחרת'):input.city}),[input,otherCity]);
 const result=useMemo(()=>estimate(config,effectiveInput),[config,effectiveInput]);
 function set<K extends keyof IntakeInput>(key:K,value:IntakeInput[K]){setInput(s=>({...s,[key]:value}));setStatus('');}
 let body='';try{body=requestText(config,effectiveInput)}catch{}
 const demo=!config.phone;
 function submit(e:FormEvent){e.preventDefault();try{requestText(config,effectiveInput);setReview(true);setStatus('');}catch(e){setStatus(e instanceof Error?e.message:'בדקו את הפרטים.')}}
 async function copy(){try{await navigator.clipboard.writeText(body);setStatus('הבקשה הועתקה. עדיין לא נשלחה.')}catch{setStatus('העתקה אוטומטית אינה זמינה. אפשר לבחור את הטקסט ולהעתיק ידנית.');textRef.current?.select()}}
 return <div className={`nx-intake ${compact?'is-compact':''}`}>
 <div className="nx-intake-bar"><span className="nx-dot"/><strong>{config.name}</strong><small>{demo?'מחירון דוגמה':'מחירון שהוזן בקישור'}</small></div>
 <div className="nx-intake-inner"><div className="nx-intake-heading"><div><p className="nx-caption">בקשת מחיר לניקוי ריפודים</p><h2>{review?'הבקשה שלכם מוכנה.':'מה מנקים היום?'}</h2></div><Icon name={review?'check':'file'} size={30}/></div>
 {!review?<form onSubmit={submit}>
 <fieldset className="nx-seat-selector"><legend>כמה מושבים בספה?</legend><div className="nx-counter"><button aria-label="הפחתת מושב" type="button" disabled={input.seats===1} onClick={()=>set('seats',input.seats-1)}>−</button><output aria-live="polite">{input.seats}</output><button aria-label="הוספת מושב" type="button" disabled={input.seats===8} onClick={()=>set('seats',input.seats+1)}>+</button><div className="nx-sofa" aria-hidden="true">{Array.from({length:Math.min(input.seats,6)},(_,i)=><i key={i}/>)}{input.seats>6&&<b>+{input.seats-6}</b>}</div></div></fieldset>
 <div className="nx-fields"><label>סוג הריפוד<select aria-label="סוג הריפוד" value={input.material} onChange={e=>set('material',e.target.value)}><option>בד רגיל</option><option>עור או בד עדין</option><option>לא בטוח</option></select></label><label>מזרן זוגי נוסף<select aria-label="מזרן זוגי נוסף" value={input.mattresses} onChange={e=>set('mattresses',Number(e.target.value))}><option value={0}>בלי מזרן</option>{[1,2,3].map(n=><option key={n} value={n}>{n} {n===1?'מזרן':'מזרנים'}</option>)}</select></label><label>באיזו עיר?<select aria-label="באיזו עיר?" value={input.city} onChange={e=>set('city',e.target.value)}>{config.cities.map(c=><option key={c}>{c}</option>)}<option value="עיר אחרת">עיר אחרת</option></select></label><label>מתי נוח לכם?<select aria-label="מתי נוח לכם?" value={input.timing} onChange={e=>set('timing',e.target.value)}><option>בהקדם</option><option>השבוע</option><option>שבוע הבא</option><option>גמיש</option></select></label></div>
 {input.city==='עיר אחרת'&&<label className="nx-field">שם העיר<input aria-label="שם העיר" required minLength={2} maxLength={50} value={otherCity} placeholder="באיזו עיר העבודה?" onChange={e=>setOtherCity(e.target.value)}/></label>}
 <label className="nx-field">שם פרטי<input name="firstName" autoComplete="given-name" value={input.name} maxLength={60} required placeholder="איך קוראים לכם?" onChange={e=>set('name',e.target.value)}/></label>
 <label className="nx-field">משהו שחשוב שנדע? <span>(לא חובה)</span><textarea value={input.notes} maxLength={600} rows={2} placeholder="למשל: שזלונג, כתם מיוחד או צורך בבדיקה" onChange={e=>set('notes',e.target.value)}/></label>
 <div className={`nx-estimate ${result.amount===null?'needs-review':''}`} aria-live="polite"><div><span>{result.amount===null?'לא מנחשים מחיר':demo?'אומדן דוגמה':'אומדן לבדיקה'}</span><strong>{result.amount===null?'צריך בדיקה אישית':`₪${result.amount.toLocaleString('he-IL')}`}</strong></div><p>{result.reason}</p></div>
 <button type="submit" className="nx-button nx-dark">לסיכום הבקשה <Icon name="arrow"/></button><p className="nx-form-note">אין כאן תשלום או קביעת תור. תמונה מצרפים ידנית בשלב הבא בוואטסאפ.</p>
 </form>:<div className="nx-review">
 <textarea ref={textRef} aria-label="סיכום הבקשה" readOnly rows={12} value={body}/>
 {demo?<div className="nx-demo-notice"><strong>אתם בתוך הדגמה.</strong><p>אין כאן מספר של עסק אמיתי, ולכן לא נפתח שליחה לנמען כלשהו.</p></div>:<><p className="nx-recipient">היעד בוואטסאפ: <b dir="ltr">+{businessPhone(config.phone)}</b><br/>השם, המספר והמחירון הוזנו על ידי יוצר הקישור ולא אומתו על ידי Shuv. בדקו את הנמען לפני השליחה.</p><label className="nx-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>בדקתי את הפרטים ואת הנמען. ברור לי שזו בקשת מחיר לבדיקה, לא הזמנה.</label></>}
 <div className="nx-review-actions">{!demo&&consent&&<a className="nx-button nx-dark" href={whatsappLink(config.phone,body)} target="_blank" rel="noopener noreferrer">פתיחה בוואטסאפ לבדיקה ושליחה <Icon name="external" size={17}/></a>}<button type="button" className="nx-button nx-line" onClick={copy}><Icon name="copy" size={17}/> העתקת הבקשה</button><button type="button" className="nx-back" onClick={()=>{setReview(false);setConsent(false);setStatus('')}}>עריכת הפרטים</button></div>
 <p className="nx-form-note">פתיחת WhatsApp אינה שליחה. שלחו שם בעצמכם וצרפו תמונה. Shuv אינו יודע אם הבקשה נשלחה או אם העסק קיבל אותה.</p>
 </div>}
 <p role="status" className="nx-status">{status}</p>
 </div></div>
}
export function RequestPage(){
 const [config,setConfig]=useState<IntakeConfig|null>(null),[error,setError]=useState('');
 useEffect(()=>{function load(){try{const params=new URLSearchParams(window.location.hash.slice(1)),c=params.get('c');setConfig(c?unpackConfig(c):DEMO_CONFIG);setError('')}catch(e){setConfig(null);setError(e instanceof Error?e.message:'הקישור לא תקין.')}}load();window.addEventListener('hashchange',load);return()=>window.removeEventListener('hashchange',load)},[]);
 return <><NextNav back/><main className="nx-request-page">{error?<div role="alert" className="nx-error-page"><h1>לא הצלחנו לפתוח את הבקשה.</h1><p>{error}</p><a className="nx-button" href="/next/">חזרה להדגמה</a></div>:config?<><p className="nx-request-label">{config.phone?'בקשה לבדיקה · לא הזמנה סופית':'הדגמה בלבד · ללא שליחה לעסק'}</p><IntakeForm config={config}/><p className="nx-request-privacy">הפרטים בטופס נשארים בזיכרון הדפדפן עד שתבחרו להעתיק או לפתוח בוואטסאפ. הם לא נשמרים ב־Shuv. רענון העמוד מוחק אותם.</p></>:<p role="status">פותחים את הטופס…</p>}<a className="nx-back" href="/next/build/">לבעלי עסקים: בנו קישור משלכם</a></main></>
}
export function OwnerBuilder(){
 const [config,setConfig]=useState<IntakeConfig>({...DEMO_CONFIG,name:'',phone:''}),[cities,setCities]=useState(DEMO_CONFIG.cities.join(', ')),[consent,setConsent]=useState(false),[link,setLink]=useState(''),[error,setError]=useState(''),[status,setStatus]=useState('');
 const linkRef=useRef<HTMLInputElement>(null);
 function update(patch:Partial<IntakeConfig>){setConfig(c=>({...c,...patch}));setLink('');setError('');setStatus('')}
 function create(e:FormEvent){e.preventDefault();try{if(!consent)throw new Error('צריך לאשר פרסום של פרטי העסק בקישור.');const valid=validateConfig({...config,cities:cities.split(',').map(s=>s.trim()).filter(Boolean)});setLink(`${window.location.origin}/next/request/#c=${packConfig(valid)}`);setError('');setStatus('הקישור נוצר בדפדפן. הוא לא נשלח לאף אחד.')}catch(e){setError(e instanceof Error?e.message:'בדקו את הפרטים.')}}
 async function copy(){try{await navigator.clipboard.writeText(link);setStatus('הקישור הועתק.')}catch{setStatus('אפשר לבחור ולהעתיק את הקישור ידנית.');linkRef.current?.select()}}
 return <><NextNav back/><main className="nx-builder"><section><span className="nx-pill">אב־טיפוס לבעלי מקצוע</span><h1>המחירון שלכם.<br/><span>בקישור אחד.</span></h1><p>מגדירים עסק, אזור ושיטת תמחור. מקבלים קישור שהלקוח יכול לפתוח בטלפון, למלא ולשלוח לכם בוואטסאפ.</p><div className="nx-builder-facts"><p><Icon name="check"/> אין צורך בהרשמה או בחיבור לחשבון WhatsApp.</p><p><Icon name="check"/> אין שליחה אוטומטית או גישה לשיחות שלכם.</p><p><Icon name="shield"/> זה קישור ציבורי ולא חתום. אפשר לשנות את הנתונים בו. המחיר שמגיע לוואטסאפ הוא בקשת בדיקה בלבד.</p></div><p className="nx-boundary">זה אינו מערכת הזמנות, סליקה או שירות שמבטיח יותר לקוחות. בודקים כאן אם פנייה מובנית חוסכת לכם עבודה.</p></section>
 <section className="nx-builder-form"><h2>נתחיל מהעסק</h2><form onSubmit={create}><label className="nx-field">שם העסק<input required maxLength={60} minLength={2} value={config.name} placeholder="שם העסק שלכם" onChange={e=>update({name:e.target.value})}/></label><label className="nx-field">מספר WhatsApp של העסק<input required inputMode="tel" type="tel" dir="ltr" value={config.phone} placeholder="05XXXXXXXX" onChange={e=>update({phone:e.target.value})}/></label><div className="nx-fields"><label>מחיר למושב ספה (₪)<input type="number" min={1} max={10000} step={1} required value={Number.isNaN(config.seat)?'':config.seat} onChange={e=>update({seat:e.target.valueAsNumber})}/></label><label>מינימום לביקור (₪)<input type="number" min={1} max={10000} step={1} required value={Number.isNaN(config.minimum)?'':config.minimum} onChange={e=>update({minimum:e.target.valueAsNumber})}/></label></div><label className="nx-field">מחיר למזרן זוגי נוסף (₪)<input type="number" min={1} max={10000} step={1} required value={Number.isNaN(config.mattress)?'':config.mattress} onChange={e=>update({mattress:e.target.valueAsNumber})}/></label><p className="nx-form-note">הסכומים המוכנים הם דוגמה בלבד. החליפו אותם במחירים שלכם ללקוח הסופי, כולל כל חיוב שצריך להיכלל. החישוב: מושבים × מחיר + מזרנים × מחיר, ולפחות המינימום לביקור.</p><label className="nx-field">ערי השירות, מופרדות בפסיקים<textarea required rows={2} maxLength={1200} value={cities} onChange={e=>{setCities(e.target.value);setLink('');setStatus('')}}/></label><label className="nx-consent"><input type="checkbox" checked={consent} onChange={e=>{setConsent(e.target.checked);if(!e.target.checked)setLink('')}} required/>אני מורשה להשתמש בפרטי העסק, ומאשר שהשם, המספר והמחירון יופיעו בקישור ציבורי.</label><p className="nx-form-note">אין כאן שמירה בענן או אפשרות לבטל קישור שכבר שותף. אל תשתפו מפתחות, פרטי לקוחות או מידע סודי.</p><button className="nx-button nx-dark" type="submit">יצירת הקישור שלי <Icon name="arrow"/></button></form>{error&&<p role="alert" className="nx-form-error">{error}</p>}{link&&<div className="nx-generated"><label>הקישור ללקוחות<input aria-label="הקישור ללקוחות" ref={linkRef} value={link} readOnly dir="ltr"/></label><button type="button" onClick={copy} className="nx-button nx-line">העתקת הקישור <Icon name="copy" size={18}/></button><a href={link} target="_blank" rel="noopener noreferrer" className="nx-back">לפתוח כמו לקוח <Icon name="external" size={16}/></a></div>}<p role="status" className="nx-status">{status}</p></section></main></>
}
