'use client';
import {useEffect,useRef} from 'react';
import {Icon} from '@/components/flow/ui';
import {IntakeForm,NextNav} from './intake';
const questions=['כמה מושבים יש בספה?','באיזו עיר אתם?','זה בד רגיל או עור?','מתי תרצו שנגיע?'];
export default function NextLanding(){
 const root=useRef<HTMLDivElement>(null),assembly=useRef<HTMLElement>(null);
 useEffect(()=>{
  const el=root.current,part=assembly.current;if(!el||!part)return;
  let raf=0;const media=matchMedia('(prefers-reduced-motion: reduce)');
  function render(){raf=0;if(!part||!el)return;const r=part.getBoundingClientRect();const mobile=innerWidth<760;const p=mobile||media.matches?1:Math.min(1,Math.max(0,-r.top/(r.height-innerHeight)));part.style.setProperty('--fold',String(p));part.dataset.fold=p<.28?'questions':p<.68?'assembling':'ready';el.style.setProperty('--hero-p',String(media.matches?0:Math.min(1,Math.max(0,scrollY/innerHeight))));}
  function schedule(){if(!raf)raf=requestAnimationFrame(render)}render();addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);media.addEventListener('change',schedule);
  const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('nx-seen')}),{threshold:.18});el.querySelectorAll('[data-nx-in]').forEach(e=>observer.observe(e));
  const mount=()=>{if(el.isConnected&&!el.hasAttribute('data-nx-mounted')&&window.ScrollCraft){el.setAttribute('data-nx-mounted','true');window.ScrollCraft.mount(el)}};
  let script=document.querySelector<HTMLScriptElement>('script[data-next-scrollcraft]');if(window.ScrollCraft)mount();else{if(!script){script=document.createElement('script');script.src='/vendor/scrollcraft.js';script.async=true;script.dataset.nextScrollcraft='true';document.body.appendChild(script)}script.addEventListener('load',mount)}
  return()=>{removeEventListener('scroll',schedule);removeEventListener('resize',schedule);media.removeEventListener('change',schedule);cancelAnimationFrame(raf);observer.disconnect();script?.removeEventListener('load',mount)};
 },[]);
 return <div className="nx-home" ref={root}><a className="nx-skip" href="#next-main">דלגו לתוכן</a><NextNav/>
 <main id="next-main"><section className="nx-hero" data-sc-act="flow"><div className="nx-grid-ground" aria-hidden="true" data-sc-parallax="-.03"/><div className="nx-hero-top"><span className="nx-pill"><span className="nx-dot"/> כיוון חדש לבדיקה</span><span className="nx-serial" dir="ltr">SHUV / A BETTER FIRST MESSAGE</span></div><div className="nx-hero-content"><h1>פחות<br/><span>הלוך־חזור.</span></h1><div className="nx-hero-side"><p>הלקוח לא צריך עוד ״שלח פרטים״.<br/><strong>הוא צריך דרך פשוטה להגיע מוכן.</strong></p><a href="#next-demo" className="nx-button">לנסות כמו לקוח <Icon name="arrow"/></a><span className="nx-small">אב־טיפוס. בלי חשבון. בלי הבטחת סגירות.</span></div></div>
 <div className="nx-hero-stage" aria-hidden="true"><div className="nx-stage-label" dir="ltr">LESS CHAT.<br/>MORE CONTEXT.</div><div className="nx-hero-rings"><i/><i/><i/></div><div className="nx-chat-slip slip-a" data-sc-parallax=".025"><span>לקוח</span><p>היי, כמה עולה לנקות ספה?</p><b>09:41</b></div><div className="nx-hero-ticket" data-sc-parallax="-.05"><div className="nx-ticket-ruler"><span>בקשה לבדיקה</span><Icon name="up" size={23}/></div><strong>ספה אחת.<br/>כל הפרטים החשובים.</strong><div className="nx-ticket-line"><span>3 מושבים · בד רגיל</span><span>אשקלון</span></div><div className="nx-ticket-total"><span>אומדן דוגמה</span><b dir="ltr">₪300</b></div><div className="nx-barcode"/><small>לא מחיר מאושר. לא הזמנה.</small></div><div className="nx-chat-slip slip-b" data-sc-parallax=".045"><Icon name="check"/><p>עכשיו אפשר לתת תשובה.</p></div></div><div className="nx-hero-foot"><span>נבנה סביב הפנייה הראשונה, לא סביב עוד דשבורד.</span><a href="/guest/">למוצר הקודם <Icon name="up" size={17}/></a></div></section>
 <section className="nx-statement"><p className="nx-caption">הבעיה שאנחנו בודקים</p><h2 data-nx-in>לא חסרות הודעות.<br/>חסרים בהן <span>הפרטים.</span></h2><p data-nx-in>בעל מקצוע צריך לדעת מה העבודה, איפה היא ומתי רוצים אותה. במקום עוד סבב שאלות, הלקוח ממלא בקשה קצרה ומגיע לוואטסאפ עם ההקשר.</p><div className="nx-small-print">לא מחזירים ליד אבוד בכוח. בודקים דרך טובה יותר להתחיל עם פנייה חדשה.</div></section>
 <section className="nx-assembly" id="next-experience" ref={assembly} aria-label="ארבע שאלות הופכות לבקשה מסודרת"><div className="nx-assembly-sticky"><div className="nx-assembly-header"><h2>פחות לאסוף.<br/><span>יותר להבין.</span></h2><p>אותה בקשה. פחות פינג־פונג.</p></div><div className="nx-paper-scene" aria-hidden="true"><div className="nx-registration"><span>קלט</span><i/><span>הקשר</span></div><div className="nx-question-stack">{questions.map((q,i)=><div className={`nx-question q-${i}`} key={q}><small>לפני הצעת המחיר</small><strong>{q}</strong><span dir="ltr">↙</span></div>)}</div><div className="nx-final-sheet"><div className="nx-sheet-head"><span>בקשה מסודרת</span><Icon name="check"/></div><h3>ניקוי ספה,<br/>בלי החלקים החסרים.</h3><dl><div><dt>מה</dt><dd>ספה, 3 מושבים</dd></div><div><dt>ריפוד</dt><dd>בד רגיל</dd></div><div><dt>איפה</dt><dd>אשקלון</dd></div><div><dt>מתי</dt><dd>השבוע</dd></div></dl><p>מוכנה להעתקה או לפתיחה בוואטסאפ.<br/>תמונה והמחיר הסופי נבדקים עם העסק.</p><div className="nx-barcode"/></div></div><p className="nx-scene-foot">המחשה של הבקשה. אין שליחה או תמחור מאושר בסצנה הזאת.</p></div></section>
 <section className="nx-demo-section" id="next-demo"><div className="nx-demo-intro"><span className="nx-pill">עכשיו אתם הלקוח</span><h2>אל תדמיינו.<br/><span>תלחצו.</span></h2><p>ניקוי ריפודים הוא התחום הראשון שבחרנו לבדוק. שנו את מספר המושבים, סוג הריפוד והעיר, ותראו בקשת מחיר נבנית מולכם.</p><div className="nx-demo-hint"><Icon name="up"/><span>ריפוד מיוחד או עיר מחוץ לאזור?<br/><strong>המערכת תבקש בדיקה, לא תנחש מחיר.</strong></span></div><p className="nx-note">כל המחירים כאן בדויים. לא נאספים פרטי לקוחות, ולא יוצאת הודעה מההדגמה.</p></div><IntakeForm compact/></section>
 <section className="nx-value"><div className="nx-value-title"><h2>הערך לא נמצא<br/>ב״בינה״.<br/><span>הוא נמצא בעבודה<br/>שלא צריך לחזור עליה.</span></h2></div><div className="nx-value-lines"><article data-nx-in><span>ללקוח</span><h3>מבינים מה צריך למלא.</h3><p>פרטי העבודה, אזור, מועד ואומדן לבדיקה במקום פנייה כללית של ״כמה עולה?״.</p></article><article data-nx-in><span>לבעל המקצוע</span><h3>מקבלים הקשר, לא רק מספר.</h3><p>הבקשה מגיעה בערוץ שכבר עובדים בו. אין חובה לפתוח מערכת נוספת כדי לקרוא אותה.</p></article><article data-nx-in><span>לנו, לפני שמוכרים</span><h3>מוכיחים חיסכון. לא מבטיחים קסם.</h3><p>צריך לבדוק עם עסק אמיתי אם הלקוחות מסיימים את הטופס ואם נחסכת עבודה. האתר הזה אינו הוכחה לביקוש או לעלייה בסגירות.</p></article></div></section>
 <section className="nx-close"><div><span className="nx-caption">בדיקה קטנה. שאלה עסקית גדולה.</span><h2>פנייה.<br/>שמגיעה.<br/><span>מוכנה.</span></h2></div><div className="nx-close-action"><p>יש לכם עסק לניקוי ריפודים?<br/>הגדירו מחירון משלכם וקבלו קישור שאפשר לפתוח מכל טלפון.</p><a className="nx-button nx-dark" href="/next/build/">בונים קישור לעסק <Icon name="arrow"/></a><p className="nx-small">בלי חיוב. בלי גישה לשיחות. בלי הרשמה.</p></div></section></main><footer className="nx-footer"><span dir="ltr">SHUV FLOW / NEXT DIRECTION</span><p>כיוון ניסיוני. המוצר הקיים נשאר זמין.</p><a href="/guest/">למוצר הקיים <Icon name="up" size={16}/></a></footer></div>
}
